---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "front"
  labels: 
    app: "front"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "front"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "front"
    spec: 
      containers: 
        - 
          name: "front"
          image: "ghcr.io/jinyoung/food-delivery6/front:v0-0-2"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "store"
  labels: 
    app: "store"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "store"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "store"
    spec: 
      containers: 
        - 
          name: "store"
          image: "ghcr.io/jinyoung/food-delivery6/store:v0-0-2"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "rider"
  labels: 
    app: "rider"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "rider"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "rider"
    spec: 
      containers: 
        - 
          name: "rider"
          image: "ghcr.io/jinyoung/food-delivery6/rider:v0-0-2"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "customer"
  labels: 
    app: "customer"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "customer"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "customer"
    spec: 
      containers: 
        - 
          name: "customer"
          image: "ghcr.io/jinyoung/food-delivery6/customer:v0-0-2"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "front"
  labels: 
    app: "front"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "front"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "store"
  labels: 
    app: "store"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "store"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "rider"
  labels: 
    app: "rider"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "rider"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "customer"
  labels: 
    app: "customer"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "customer"

